name : Github Repo Checkout
on: push
jobs:
  Github_Checkout:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the code
         uses: actions/checkout@v6
       - name: Print index.html file
         run: cat index.html; pwd
 
    
