name: CI/CD Workflow Demo
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "This is build step"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "This is test step"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "This is deploy step"
